version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"


  database:
    image: mysql:5.7
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"

