version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - db_network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  database:
    image: mysql:5.7
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - /data/db:/data/db
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
